import { LanguageListDto } from "src/app/common/models/languageListDto";

export class ECollectionReviewDto {
    recId!: string;
    propertyId!: string;
    eCollectionPacketType!: number;
    eMail!: string;
    amount!: number;
    currencyid!: string;
    rate!: number;
    fullName!: string;
    // recordEMail: string;
    eCollectionEndType!: number;
    endDate!: Date;
    // paidDate: Date;
    // connectedRecords: string;
    endTime!: string;
    selectedVirtualPosId!: string;
    selectedLanguageCode!: number;
    undoInstallment!: boolean;
    payeeNote!: string;
    deleted!: boolean;
    symbol!: string;
    images!: string;
    favimageurl!: string;
    code!: string;
    successFailResponse!: string;
    virtualPosId!: string;
    cancel!: boolean;
    paymentInfo!: string;
    installment!: string;
    paid!: boolean;
    isRefund!: boolean;
    currentcode!: string;
    currentremark!: string;
    cardInfo!: string;
    commissionByBank!: number;
    amountByBank!: number;
    //bankTransferList: BankTransferInfoDto[] = [];
    accountHolder!: string;
    accountHolderList: LanguageListDto[] = [];
    preWriting!: string;
    preWritingList: LanguageListDto[] = [];
    isPrePaymentActive!: boolean;
    prePaymentRates!: string;
    maleControlRemark!: string;
    maleControlRemarkList: LanguageListDto[] = [];
    contractIds!: string[];
    transferDetailRemark!: string;
    transferDetailRemarkList: LanguageListDto[] = [];
}
